library(shiny)
library(shinythemes)
library(shinyWidgets)
library(shinyjs)
library(shinycssloaders)
library(shinyBS)
library(shinyhelper)
library(DT)
library(formattable)
# library(plyr)
library(tidyverse)
library(ggrepel)
library(hrbrthemes)
library(intubate)
library(broom)
library(magrittr)
library(crossdes)
library(sensR)
library(BradleyTerry2)
library(SensoMineR)
library(lmerTest)
library(car)
library(RVAideMemoire)

invisible(map(list.files("modules", full.names = TRUE), source))
invisible(map(list.files("helpers", full.names = TRUE), source))
# CSS loaders
options(spinner.type = 5, spinner.color = "#34495e")